name: "综合 Bug 反馈"
description: "有功能有问题"
assignees: "langningchen"
labels: "bug,needs-triage"
title: "[Bug] "
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我已确认了XMOJ增强脚本已为最新版，且最新版未修复这个 Bug。"
      required: true
    - label: "我已在 [Issues 页面](https://github.com/langningchen/XMOJ-Script/Issues) 中搜索，确认了这一 Bug 未被提交过。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述
    description: "详细描述该 Bug 的具体表现。"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 重现步骤
    description: "详细描述要怎么操作才能再次触发这个 Bug。"
- type: textarea
  id: "yml-4"
  attributes:
    label: 控制台错误信息
    description: "粘贴控制台错误信息，如果没有错误请忽略"
    placeholder: "请按F12并选择控制台/Console，并将其中的错误信息粘贴至此处"
