name: Auto assign issues

on:
  issues:
    - opened
    - unassigned
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Assign issues
      uses: gustavofreze/auto-assign@1.0.0
      with:
        assignees: 'langningchen'
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        assignment_options: 'ISSUE'
